import type { Position, RosterSlot } from "./types";

export const REFRESH_MS = 2 * 60 * 60 * 1000;
export const SALARY_CAP = 50_000;
export const POSITIONS: Position[] = ["QB", "RB", "WR", "TE", "DST"];

export const ROSTER: { slot: RosterSlot; positions: Position[] }[] = [
  { slot: "QB", positions: ["QB"] },
  { slot: "RB", positions: ["RB"] },
  { slot: "RB2", positions: ["RB"] },
  { slot: "WR", positions: ["WR"] },
  { slot: "WR2", positions: ["WR"] },
  { slot: "WR3", positions: ["WR"] },
  { slot: "TE", positions: ["TE"] },
  { slot: "FLEX", positions: ["RB", "WR", "TE"] },
  { slot: "DST", positions: ["DST"] },
];

export const SLOT_LABEL: Record<RosterSlot, string> = {
  QB: "QB",
  RB: "RB",
  RB2: "RB",
  WR: "WR",
  WR2: "WR",
  WR3: "WR",
  TE: "TE",
  FLEX: "FLEX",
  DST: "DST",
};

export const ESPN_POS: Record<number, Position | undefined> = {
  1: "QB",
  2: "RB",
  3: "WR",
  4: "TE",
  16: "DST",
};

export const ESPN_TEAMS: Record<number, { abbr: string; nick: string }> = {
  1: { abbr: "ATL", nick: "Falcons" },
  2: { abbr: "BUF", nick: "Bills" },
  3: { abbr: "CHI", nick: "Bears" },
  4: { abbr: "CIN", nick: "Bengals" },
  5: { abbr: "CLE", nick: "Browns" },
  6: { abbr: "DAL", nick: "Cowboys" },
  7: { abbr: "DEN", nick: "Broncos" },
  8: { abbr: "DET", nick: "Lions" },
  9: { abbr: "GB", nick: "Packers" },
  10: { abbr: "TEN", nick: "Titans" },
  11: { abbr: "IND", nick: "Colts" },
  12: { abbr: "KC", nick: "Chiefs" },
  13: { abbr: "LV", nick: "Raiders" },
  14: { abbr: "LAR", nick: "Rams" },
  15: { abbr: "MIA", nick: "Dolphins" },
  16: { abbr: "MIN", nick: "Vikings" },
  17: { abbr: "NE", nick: "Patriots" },
  18: { abbr: "NO", nick: "Saints" },
  19: { abbr: "NYG", nick: "Giants" },
  20: { abbr: "NYJ", nick: "Jets" },
  21: { abbr: "PHI", nick: "Eagles" },
  22: { abbr: "ARI", nick: "Cardinals" },
  23: { abbr: "PIT", nick: "Steelers" },
  24: { abbr: "LAC", nick: "Chargers" },
  25: { abbr: "SF", nick: "49ers" },
  26: { abbr: "SEA", nick: "Seahawks" },
  27: { abbr: "TB", nick: "Buccaneers" },
  28: { abbr: "WAS", nick: "Commanders" },
  29: { abbr: "CAR", nick: "Panthers" },
  30: { abbr: "JAX", nick: "Jaguars" },
  33: { abbr: "BAL", nick: "Ravens" },
  34: { abbr: "HOU", nick: "Texans" },
};

/** ESPN fantasy stat ids */
export const S = {
  passCmp: 0,
  passAtt: 1,
  passYds: 3,
  passTd: 4,
  int: 20,
  rushAtt: 23,
  rushYds: 24,
  rushTd: 25,
  recYds: 42,
  recTd: 43,
  recYdsAlt: 42,
  receptions: 53,
  recCatch: 53,
  targets: 58,
  fumLost: 72,
  sacks: 89,
  defInt: 90,
  fumRec: 91,
  defTd: 93,
  defTdAlt: 103,
  ptsAllowed: 95,
  ydsAllowed: 96,
  games: 210,
};

export const TEAM_LOOKUP: Record<string, string> = {
  ari: "ARI",
  arizona: "ARI",
  cardinals: "ARI",
  atl: "ATL",
  atlanta: "ATL",
  falcons: "ATL",
  bal: "BAL",
  baltimore: "BAL",
  ravens: "BAL",
  buf: "BUF",
  buffalo: "BUF",
  bills: "BUF",
  car: "CAR",
  carolina: "CAR",
  panthers: "CAR",
  chi: "CHI",
  chicago: "CHI",
  bears: "CHI",
  cin: "CIN",
  cincinnati: "CIN",
  bengals: "CIN",
  cle: "CLE",
  cleveland: "CLE",
  browns: "CLE",
  dal: "DAL",
  dallas: "DAL",
  cowboys: "DAL",
  den: "DEN",
  denver: "DEN",
  broncos: "DEN",
  det: "DET",
  detroit: "DET",
  lions: "DET",
  gb: "GB",
  greenbay: "GB",
  packers: "GB",
  hou: "HOU",
  houston: "HOU",
  texans: "HOU",
  ind: "IND",
  indianapolis: "IND",
  colts: "IND",
  jax: "JAX",
  jac: "JAX",
  jacksonville: "JAX",
  jaguars: "JAX",
  jags: "JAX",
  kc: "KC",
  kansascity: "KC",
  chiefs: "KC",
  lv: "LV",
  lasvegas: "LV",
  oakland: "LV",
  raiders: "LV",
  lac: "LAC",
  losangeleschargers: "LAC",
  chargers: "LAC",
  lar: "LAR",
  losangelesrams: "LAR",
  rams: "LAR",
  mia: "MIA",
  miami: "MIA",
  dolphins: "MIA",
  min: "MIN",
  minnesota: "MIN",
  vikings: "MIN",
  ne: "NE",
  newengland: "NE",
  patriots: "NE",
  no: "NO",
  neworleans: "NO",
  saints: "NO",
  nyg: "NYG",
  newyorkgiants: "NYG",
  giants: "NYG",
  nyj: "NYJ",
  newyorkjets: "NYJ",
  jets: "NYJ",
  phi: "PHI",
  philadelphia: "PHI",
  eagles: "PHI",
  pit: "PIT",
  pittsburgh: "PIT",
  steelers: "PIT",
  sf: "SF",
  sanfrancisco: "SF",
  "49ers": "SF",
  niners: "SF",
  sea: "SEA",
  seattle: "SEA",
  seahawks: "SEA",
  tb: "TB",
  tampabay: "TB",
  buccaneers: "TB",
  bucs: "TB",
  ten: "TEN",
  tennessee: "TEN",
  titans: "TEN",
  was: "WAS",
  washington: "WAS",
  commanders: "WAS",
  footballteam: "WAS",
  wsh: "WAS",
};

export function canonTeam(raw: string | null | undefined): string {
  if (!raw) return "";
  const k = raw.toLowerCase().replace(/[^a-z0-9]/g, "");
  if (TEAM_LOOKUP[k]) return TEAM_LOOKUP[k]!;
  const parts = raw.trim().split(/\s+/);
  const last = parts[parts.length - 1]?.toLowerCase().replace(/[^a-z0-9]/g, "");
  if (last && TEAM_LOOKUP[last]) return TEAM_LOOKUP[last]!;
  if (k.includes("49ers") || k.includes("niners")) return "SF";
  if (/^[A-Z]{2,3}$/.test(raw.trim())) return TEAM_LOOKUP[raw.trim().toLowerCase()] ?? raw.trim().toUpperCase();
  return raw.toUpperCase();
}
