import type { NbaPos, NbaSlot } from "./types";

export const NBA_CAP = 50_000;
export const NBA_REFRESH_MS = 2 * 60 * 60 * 1000;
export const NBA_POS: NbaPos[] = ["PG", "SG", "SF", "PF", "C"];

export const NBA_ROSTER: { slot: NbaSlot; positions: NbaPos[] }[] = [
  { slot: "PG", positions: ["PG"] },
  { slot: "SG", positions: ["SG"] },
  { slot: "SF", positions: ["SF"] },
  { slot: "PF", positions: ["PF"] },
  { slot: "C", positions: ["C"] },
  { slot: "G", positions: ["PG", "SG"] },
  { slot: "F", positions: ["SF", "PF"] },
  { slot: "UTIL", positions: ["PG", "SG", "SF", "PF", "C"] },
];

export const NBA_SLOT_LABEL: Record<NbaSlot, string> = {
  PG: "PG",
  SG: "SG",
  SF: "SF",
  PF: "PF",
  C: "C",
  G: "G",
  F: "F",
  UTIL: "UTIL",
};

/** ESPN defaultPositionId */
export const ESPN_NBA_POS: Record<number, NbaPos> = {
  1: "PG",
  2: "SG",
  3: "SF",
  4: "PF",
  5: "C",
};

export const ESPN_NBA_TEAMS: Record<number, string> = {
  1: "ATL",
  2: "BOS",
  3: "NOP",
  4: "CHI",
  5: "CLE",
  6: "DAL",
  7: "DEN",
  8: "DET",
  9: "GSW",
  10: "HOU",
  11: "IND",
  12: "LAC",
  13: "LAL",
  14: "MIA",
  15: "MIL",
  16: "MIN",
  17: "BKN",
  18: "NYK",
  19: "ORL",
  20: "PHI",
  21: "PHX",
  22: "POR",
  23: "SAC",
  24: "SAS",
  25: "OKC",
  26: "UTA",
  27: "WAS",
  28: "TOR",
  29: "MEM",
  30: "CHA",
};

export const NBA_TEAM_LOOKUP: Record<string, string> = {
  atl: "ATL",
  atlanta: "ATL",
  atlantahawks: "ATL",
  hawks: "ATL",
  bos: "BOS",
  boston: "BOS",
  bostonceltics: "BOS",
  celtics: "BOS",
  bkn: "BKN",
  bro: "BKN",
  brooklyn: "BKN",
  brooklynnets: "BKN",
  nets: "BKN",
  cha: "CHA",
  charlotte: "CHA",
  charlottehornets: "CHA",
  hornets: "CHA",
  chi: "CHI",
  chicago: "CHI",
  chicagobulls: "CHI",
  bulls: "CHI",
  cle: "CLE",
  cleveland: "CLE",
  clevelandcavaliers: "CLE",
  cavs: "CLE",
  cavaliers: "CLE",
  dal: "DAL",
  dallas: "DAL",
  dallasmavericks: "DAL",
  mavs: "DAL",
  mavericks: "DAL",
  den: "DEN",
  denver: "DEN",
  denvernuggets: "DEN",
  nuggets: "DEN",
  det: "DET",
  detroit: "DET",
  detroitpistons: "DET",
  pistons: "DET",
  gs: "GSW",
  gsw: "GSW",
  goldenstate: "GSW",
  goldenstatewarriors: "GSW",
  warriors: "GSW",
  gol: "GSW",
  hou: "HOU",
  houston: "HOU",
  houstonrockets: "HOU",
  rockets: "HOU",
  ind: "IND",
  indiana: "IND",
  indianapacers: "IND",
  pacers: "IND",
  lac: "LAC",
  clippers: "LAC",
  laclippers: "LAC",
  losangelesclippers: "LAC",
  lal: "LAL",
  lakers: "LAL",
  lalakers: "LAL",
  losangeleslakers: "LAL",
  mem: "MEM",
  memphis: "MEM",
  memphisgrizzlies: "MEM",
  grizzlies: "MEM",
  mia: "MIA",
  miami: "MIA",
  miamiheat: "MIA",
  heat: "MIA",
  mil: "MIL",
  milwaukee: "MIL",
  milwaukeebucks: "MIL",
  bucks: "MIL",
  min: "MIN",
  minnesota: "MIN",
  minnesotatimberwolves: "MIN",
  wolves: "MIN",
  timberwolves: "MIN",
  nop: "NOP",
  no: "NOP",
  neworleans: "NOP",
  neworleanspelicans: "NOP",
  pelicans: "NOP",
  ny: "NYK",
  nyk: "NYK",
  newyork: "NYK",
  newyorkknicks: "NYK",
  knicks: "NYK",
  okc: "OKC",
  okl: "OKC",
  oklahoma: "OKC",
  oklahomacity: "OKC",
  oklahomacitythunder: "OKC",
  thunder: "OKC",
  orl: "ORL",
  orlando: "ORL",
  orlandomagic: "ORL",
  magic: "ORL",
  phi: "PHI",
  philadelphia: "PHI",
  philadelphia76ers: "PHI",
  sixers: "PHI",
  phx: "PHX",
  phoenix: "PHX",
  phoenixsuns: "PHX",
  suns: "PHX",
  por: "POR",
  portland: "POR",
  portlandtrailblazers: "POR",
  blazers: "POR",
  trailblazers: "POR",
  sac: "SAC",
  sacramento: "SAC",
  sacramentokings: "SAC",
  kings: "SAC",
  sa: "SAS",
  sas: "SAS",
  san: "SAS",
  sanantonio: "SAS",
  sanantoniospurs: "SAS",
  spurs: "SAS",
  tor: "TOR",
  toronto: "TOR",
  torontoraptors: "TOR",
  raptors: "TOR",
  uta: "UTA",
  utah: "UTA",
  utahjazz: "UTA",
  jazz: "UTA",
  was: "WAS",
  washington: "WAS",
  washingtonwizards: "WAS",
  wizards: "WAS",
  wsh: "WAS",
};
