/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiNbaSlateRouteImport } from './routes/api/nba-slate'
import { Route as ApiSlateRouteImport } from './routes/api/slate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNbaSlateRoute = ApiNbaSlateRouteImport.update({
  id: '/api/nba-slate',
  path: '/api/nba-slate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlateRoute = ApiSlateRouteImport.update({
  id: '/api/slate',
  path: '/api/slate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/nba-slate': typeof ApiNbaSlateRoute
  '/api/slate': typeof ApiSlateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/nba-slate': typeof ApiNbaSlateRoute
  '/api/slate': typeof ApiSlateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/nba-slate': typeof ApiNbaSlateRoute
  '/api/slate': typeof ApiSlateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/nba-slate' | '/api/slate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/nba-slate' | '/api/slate'
  id: '__root__' | '/' | '/$' | '/api/nba-slate' | '/api/slate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiNbaSlateRoute: typeof ApiNbaSlateRoute
  ApiSlateRoute: typeof ApiSlateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nba-slate': {
      id: '/api/nba-slate'
      path: '/api/nba-slate'
      fullPath: '/api/nba-slate'
      preLoaderRoute: typeof ApiNbaSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slate': {
      id: '/api/slate'
      path: '/api/slate'
      fullPath: '/api/slate'
      preLoaderRoute: typeof ApiSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiNbaSlateRoute: ApiNbaSlateRoute,
  ApiSlateRoute: ApiSlateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
